### ISSUE TITLE
Problem compiling picosat_elixir

### ISSUE THREAD

**Issue by m0rt3nlund** [burrito-elixir/burrito#134]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**:  Docker Debian Bullseye
**Host CPU**:x 86_64 

Please run `zig version` in your Burrito project directory and write the version here:
0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here:
1.15.4
------

### Target

**Host OS**: Windows
**Host CPU**: x86_64

------

I am not sure if this is a burrito problem or if it is a `picosat_elixir` problem but I get this while trying to compile and I am unable to figure it out:

```
52.41 --> Going to recompile NIF for cross-build: picosat_elixir -> x86_64-windows
52.58 rm -f /app/deps/picosat_elixir/priv/lib/picosat_elixir/priv/picosat_nif.so
52.58 rm -f /app/deps/picosat_elixir/priv/*.o
52.58 zig cc -target x86_64-windows -O2 -dynamic -shared -Wl,-undefined=dynamic_lookup -std=c99 -finline-functions -Wall -O3 -DNDEBUG -fPIC -I /tmp/unpacked_erts_F32707FEA96460E8/otp-windows/erts-14.2.2/include -o /app/deps/picosat_elixir/priv/picosat.o -c /app/deps/picosat_elixir/c_src/picosat.c
52.60 /app/deps/picosat_elixir/c_src/picosat.c:2282:50: warning: variable 'count_resolved' set but not used [-Wunused-but-set-variable]
52.60   unsigned num_true, num_undef, num_false, size, count_resolved;
52.60                                                  ^
52.61 /app/deps/picosat_elixir/c_src/picosat.c:5334:12: warning: variable 'collect' set but not used [-Wunused-but-set-variable]
52.61   unsigned collect, delta;
52.61            ^
52.61 /app/deps/picosat_elixir/c_src/picosat.c:6467:12: warning: variable 'num_non_false' set but not used [-Wunused-but-set-variable]
52.61   unsigned num_non_false;
52.61            ^
52.63 /app/deps/picosat_elixir/c_src/picosat.c:8149:10: fatal error: 'sys/resource.h' file not found
52.63 #include <sys/resource.h>
52.63          ^~~~~~~~~~~~~~~~
52.63 3 warnings and 1 error generated.
52.63 make: *** [Makefile:49: /app/deps/picosat_elixir/priv/picosat.o] Error 1
52.63 --> Failed to rebuild picosat_elixir for x86_64-windows!
```

**Comment by m0rt3nlund** [comment]
This might be a `picosat_elixir` problem so I make an issue there as well: https://github.com/bitwalker/picosat_elixir/issues/10

**Comment by doawoo** [comment]
This is also certainly due to the makefile picking incorrect defines for the platform (which makes sense, since auto-detecting the platform would return the wrong OS even if we override the compile flags etc.)

The best option for this NIF seems to be defining the `UNAME_SYS` env variable to be the correct target. I'm working on adding a feature to burrito that will let you define CFLAGS and addition env variables that the NIF Recompiler can use! That should enable you to work with this NIF.

**Comment by doawoo** [comment]
Hey there! I just release Burrito v1.0.4 to Hex. Here's what I suggest:

1. Use the new build qualifiers on your Linux build to add `make` args and C defines to your target like this: ``

```elixir
linux: [os: :linux, cpu: :x86_64, nif_cflags: "-DNGETRUSAGE", nif_make_args: ["UNAME_SYS=Linux"]],
```

This should enable your Linux builds...

2. For windows, things are bit more tricky, since it's using a `Makefile.win` that's not compatible with `zig cc` (it cannot accept MSVC command line arguments). For this build target, I would set `skip_nifs` to `true` so Burrito won't try to recompile it, then define a custom build step (see README for more details) that copies in a pre-compiled NIF DLL for windows. 

It's certainly not as convenient but it would enable seamless builds.

**Comment by doawoo** [comment]
Closing this for now, the best bet is to fork the NIF and fix the makefile issues...
