### ISSUE TITLE
Old Zig Version required

### ISSUE THREAD

**Issue by Anonyfox** [burrito-elixir/burrito#145]
> Your Zig version does not match the one Burrito requires! We need `0.11.0`, you have: `0.13.0`

Building on a new mac, its somewhat tedious to try to downgrade a `brew install zig` to a specific version of zig. Is it really strictly needed or could we have a more "minimum" version instead of exact?

**Comment by doawoo** [comment]
I recommend using `asdf` or `mise` or Nix if you're feeling adventurous to manage your local development versions so you can easily switch between versions.

We currently lock to a Zig version due to how many breaking changes occur between even just 1 version bump of Zig (this is just the nature of how Zig evolves right now in its current form).

However- I do think we should bump our Zig requirement. I can probably look into that today!

**Comment by doawoo** [comment]
Update: I'm working through the updates required for Zig `0.13.0` -- it's mostly a few changes in the `build.zig` that need to fixed up.

**Comment by doawoo** [comment]
Good news! I've just merged in everything for Zig `0.13.0` -- I will be pushing a Hex.pm release shortly :)
